# Generated by Django 4.2.4 on 2023-08-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlisting_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageUrl',
            field=models.URLField(max_length=350),
        ),
    ]
