# Generated by Django 4.2.4 on 2023-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_commentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='time_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
