# Generated by Django 4.2.4 on 2023-08-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_commentsection_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsection',
            old_name='body',
            new_name='comment',
        ),
    ]
