# Generated by Django 4.2.4 on 2023-08-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_auctionlisting_current_price_alter_bid_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
