# Generated by Django 4.2.4 on 2023-08-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_bid_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='commentsection',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentsection',
            name='post',
        ),
        migrations.DeleteModel(
            name='AuctionListing',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CommentSection',
        ),
    ]
